# Make sure to check the documentation at https://goreleaser.com
env:
  - GIT_URL=https://github.com/soulteary/yi-openai-proxy
before:
  hooks:
    - go mod tidy
builds:
  - id: yi-openai-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd
    binary: yi-openai-proxy
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildDate={{ .Date }}
      - -X main.gitCommit={{ .Commit }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# https://goreleaser.com/customization/changelog/
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^build:'
      - '^ci:'
#      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^feat(deps):'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
      - '^Update'
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 400
#    - title: 'Build process updates'
#      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
#      order: 400
    - title: Other work
      order: 9999
release:
  footer: |
    **Full Changelog**: https://github.com/soulteary/yi-openai-proxy/compare/{{ .PreviousTag }}...{{ .Tag }}
